# --- Serving options --- #
# If you are building a GitHub project page then use these settings:
# url is the full website URL
url: "http://uvic-econ.github.io/econ457-fa16"
# baseurl is the website's URL without the hostname
baseurl: "/econ457-fa16"

# Name of website
title: econ457-fa16

# Short description of your site
description: ECON 457.

# --- Navigation bar options --- #
# Image to show in the navigation bar - image must be a square (width = height)
avatar: 
#"/img/MTH107Logo.jpg"
navbar-links:
  Book: "book"
  Modules: "modules"
  Resources: "resources"
  Syllabus: "resources/Syllabus-Current"
  Dates: "resources/Dates-Current"
#  Derek: "../aboutme"

# --- Footer options --- #
author:
  name: Jon Duan
  email: "jonduan@uvic.ca"

# Select which links to show in the footer
footer-links-active:
  email: true
  github: false
  twitter: false
  facebook: false
  rss: false
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
url-pretty: "http://uvic-econ.github.io/econ457-fa16"

# --- Pagination options --- #
paginate: 6

# --- Don't need to touch anything below here (but you can if you want) --- #
# Output options (more information on Jekyll's site)
timezone: "America/Vancouver"
markdown: kramdown
highlighter: Rouge
permalink: /:year-:month-:day-:title

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false  # change to false

# Exclude these files from production site
exclude:
  - CNAME
  - LICENSE
  - README.md

# prose.io options
prose:
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - /_includes
    - /_layouts
    - /css
    - /img
    - /js
